"""payment declarations

Revision ID: a615391ee0a3
Revises: 0527e8973f16
Created: 2026-10-07 20:22:15.663549+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a615391ee0a3'
down_revision = '0527e8973f16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_declaration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('taxpayer_id', sa.Integer(), nullable=False),
    sa.Column('fee_quote_id', sa.Integer(), nullable=True),
    sa.Column('bucket', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by', sa.String(length=320), nullable=True),
    sa.Column('bank_reference', sa.String(length=128), nullable=True),
    sa.Column('trust_entry_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fee_quote_id'], ['fee_quote.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['taxpayer_id'], ['taxpayer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trust_entry_id'], ['trust_entry.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_declaration', schema=None) as batch_op:
        batch_op.create_index('ix_declaration_reference', ['reference'], unique=False)
        batch_op.create_index('ix_declaration_status_time', ['status', 'at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_declaration_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_declaration_taxpayer_id'), ['taxpayer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_declaration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_declaration_taxpayer_id'))
        batch_op.drop_index(batch_op.f('ix_payment_declaration_reference'))
        batch_op.drop_index('ix_declaration_status_time')
        batch_op.drop_index('ix_declaration_reference')

    op.drop_table('payment_declaration')
    # ### end Alembic commands ###
