"""initial schema

Revision ID: 0527e8973f16
Revises: 
Created: 2026-10-07 07:03:29.551401+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0527e8973f16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('mobile_e164', sa.String(length=20), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('mobile_verified_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_email'), ['email'], unique=True)

    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=320), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.create_index('ix_audit_account_time', ['account_id', 'at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_event_account_id'), ['account_id'], unique=False)

    op.create_table('remittance_batch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('jurisdiction', sa.String(length=8), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('auth_challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('destination', sa.String(length=320), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_challenge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_challenge_destination'), ['destination'], unique=False)

    op.create_table('taxpayer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('relationship_to_filer', sa.String(length=24), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('ssn_encrypted', sa.Text(), nullable=True),
    sa.Column('ssn_index', sa.String(length=64), nullable=True),
    sa.Column('ssn_last4', sa.String(length=4), nullable=True),
    sa.Column('ssn_kind', sa.String(length=8), nullable=True),
    sa.Column('ssn_verified_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('mobile_e164', sa.String(length=20), nullable=True),
    sa.Column('resident_state', sa.String(length=2), nullable=True),
    sa.Column('is_blind', sa.Boolean(), nullable=False),
    sa.Column('can_be_claimed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'ssn_index', name='uq_taxpayer_account_ssn')
    )
    with op.batch_alter_table('taxpayer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_taxpayer_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_taxpayer_ssn_index', ['ssn_index'], unique=False)

    op.create_table('estimate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxpayer_id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('filing_status', sa.String(length=32), nullable=False),
    sa.Column('resident_state', sa.String(length=2), nullable=True),
    sa.Column('federal_agi', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('federal_taxable_income', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('federal_tax', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('federal_withheld', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('federal_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('state_tax', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('state_withheld', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('state_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('effective_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('marginal_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('selected_options', sa.JSON(), nullable=False),
    sa.Column('params_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['taxpayer_id'], ['taxpayer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estimate', schema=None) as batch_op:
        batch_op.create_index('ix_estimate_lookup', ['taxpayer_id', 'tax_year', 'method'], unique=False)
        batch_op.create_index(batch_op.f('ix_estimate_taxpayer_id'), ['taxpayer_id'], unique=False)

    op.create_table('filing_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxpayer_id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=8), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('filed_on', sa.Date(), nullable=True),
    sa.Column('accepted_on', sa.Date(), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('balance_due', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('confirmation_number', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['taxpayer_id'], ['taxpayer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taxpayer_id', 'tax_year', 'jurisdiction', 'state_code', name='uq_filing_year_jurisdiction')
    )
    with op.batch_alter_table('filing_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_filing_record_taxpayer_id'), ['taxpayer_id'], unique=False)

    op.create_table('tax_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxpayer_id', sa.Integer(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('employer_name', sa.String(length=200), nullable=True),
    sa.Column('employer_ein_encrypted', sa.Text(), nullable=True),
    sa.Column('employer_ein_last4', sa.String(length=4), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('raw_blob', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('parse_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('parse_warnings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['taxpayer_id'], ['taxpayer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tax_document', schema=None) as batch_op:
        batch_op.create_index('ix_document_year', ['taxpayer_id', 'tax_year', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_document_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_tax_document_taxpayer_id'), ['taxpayer_id'], unique=False)

    op.create_table('trust_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('taxpayer_id', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.String(length=12), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=True),
    sa.Column('reference', sa.String(length=128), nullable=True),
    sa.Column('tax_year', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['taxpayer_id'], ['taxpayer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trust_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trust_entry_taxpayer_id'), ['taxpayer_id'], unique=False)
        batch_op.create_index('ix_trust_taxpayer_time', ['taxpayer_id', 'at'], unique=False)

    op.create_table('fee_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxpayer_id', sa.Integer(), nullable=False),
    sa.Column('estimate_id', sa.Integer(), nullable=True),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('add_ons', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=32), nullable=True),
    sa.Column('payment_reference', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimate.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['taxpayer_id'], ['taxpayer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fee_quote', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_quote_taxpayer_id'), ['taxpayer_id'], unique=False)

    op.create_table('payment_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimate_id', sa.Integer(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=8), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('instalments', sa.Integer(), nullable=False),
    sa.Column('instalment_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('first_due_on', sa.Date(), nullable=True),
    sa.Column('setup_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('projected_interest', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('projected_penalty', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('bank_routing_encrypted', sa.Text(), nullable=True),
    sa.Column('bank_account_encrypted', sa.Text(), nullable=True),
    sa.Column('bank_account_last4', sa.String(length=4), nullable=True),
    sa.Column('bank_account_type', sa.String(length=16), nullable=True),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimate.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_plan_estimate_id'), ['estimate_id'], unique=False)

    op.create_table('remittance_authorization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taxpayer_id', sa.Integer(), nullable=False),
    sa.Column('estimate_id', sa.Integer(), nullable=True),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=8), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('authorized_at', sa.DateTime(), nullable=False),
    sa.Column('authorized_ip', sa.String(length=64), nullable=True),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('remitted_at', sa.DateTime(), nullable=True),
    sa.Column('confirmation_number', sa.String(length=64), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['remittance_batch.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimate.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['taxpayer_id'], ['taxpayer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('remittance_authorization', schema=None) as batch_op:
        batch_op.create_index('ix_auth_taxpayer_year', ['taxpayer_id', 'tax_year', 'jurisdiction'], unique=False)
        batch_op.create_index(batch_op.f('ix_remittance_authorization_taxpayer_id'), ['taxpayer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remittance_authorization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_remittance_authorization_taxpayer_id'))
        batch_op.drop_index('ix_auth_taxpayer_year')

    op.drop_table('remittance_authorization')
    with op.batch_alter_table('payment_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_plan_estimate_id'))

    op.drop_table('payment_plan')
    with op.batch_alter_table('fee_quote', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_quote_taxpayer_id'))

    op.drop_table('fee_quote')
    with op.batch_alter_table('trust_entry', schema=None) as batch_op:
        batch_op.drop_index('ix_trust_taxpayer_time')
        batch_op.drop_index(batch_op.f('ix_trust_entry_taxpayer_id'))

    op.drop_table('trust_entry')
    with op.batch_alter_table('tax_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tax_document_taxpayer_id'))
        batch_op.drop_index(batch_op.f('ix_tax_document_checksum'))
        batch_op.drop_index('ix_document_year')

    op.drop_table('tax_document')
    with op.batch_alter_table('filing_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_filing_record_taxpayer_id'))

    op.drop_table('filing_record')
    with op.batch_alter_table('estimate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estimate_taxpayer_id'))
        batch_op.drop_index('ix_estimate_lookup')

    op.drop_table('estimate')
    with op.batch_alter_table('taxpayer', schema=None) as batch_op:
        batch_op.drop_index('ix_taxpayer_ssn_index')
        batch_op.drop_index(batch_op.f('ix_taxpayer_account_id'))

    op.drop_table('taxpayer')
    with op.batch_alter_table('auth_challenge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_challenge_destination'))

    op.drop_table('auth_challenge')
    op.drop_table('remittance_batch')
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_event_account_id'))
        batch_op.drop_index('ix_audit_account_time')

    op.drop_table('audit_event')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_email'))

    op.drop_table('account')
    # ### end Alembic commands ###
