"""agent task queue

Revision ID: 9ff5b0e90f80
Revises: a615391ee0a3
Created: 2026-10-08 03:25:25.745476+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '9ff5b0e90f80'
down_revision = 'a615391ee0a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('taxpayer_id', sa.Integer(), nullable=True),
    sa.Column('tax_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('proposal', sa.Text(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('requires_human', sa.String(length=200), nullable=True),
    sa.Column('stale_after', sa.DateTime(), nullable=True),
    sa.Column('acted_at', sa.DateTime(), nullable=True),
    sa.Column('acted_by', sa.String(length=320), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['taxpayer_id'], ['taxpayer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_task_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_task_kind'), ['kind'], unique=False)
        batch_op.create_index('ix_agent_task_queue', ['status', 'priority', 'at'], unique=False)
        batch_op.create_index('ix_agent_task_subject', ['taxpayer_id', 'kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_task_taxpayer_id'), ['taxpayer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_task_taxpayer_id'))
        batch_op.drop_index('ix_agent_task_subject')
        batch_op.drop_index('ix_agent_task_queue')
        batch_op.drop_index(batch_op.f('ix_agent_task_kind'))
        batch_op.drop_index(batch_op.f('ix_agent_task_fingerprint'))

    op.drop_table('agent_task')
    # ### end Alembic commands ###
