"""payment receipts

Revision ID: 4a72e9ee013e
Revises: 9ff5b0e90f80
Created: 2026-10-08 03:33:35.790271+00:00
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '4a72e9ee013e'
down_revision = '9ff5b0e90f80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_declaration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('receipt_channels', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_declaration', schema=None) as batch_op:
        batch_op.drop_column('receipt_channels')
        batch_op.drop_column('receipt_sent_at')

    # ### end Alembic commands ###
